import { Seat } from "./models/Seat";

// data will come from api 

export const AllSeats: Seat[] = [
    {id: 1,available: true,seatNumber: 1 ,row:"A"},
    {id: 2,available: false,seatNumber: 2 ,row:"A"},
    {id: 3,available: true,seatNumber: 3 ,row:"A"},
    {id: 4,available: true,seatNumber: 4 ,row:"A"},
    {id: 5,available: false,seatNumber: 5 ,row:"A"},
    {id: 6,available: false,seatNumber: 6 ,row:"A"},
    {id: 7,available: true,seatNumber: 7 ,row:"A"},
    {id: 8,available: false,seatNumber: 8 ,row:"A"},
    {id: 9,available: false,seatNumber: 9 ,row:"A"},
    {id: 10,available: true,seatNumber: 10 ,row:"A"},
    {id: 11,available: true,seatNumber: 11 ,row:"A"},
    {id: 12,available: true,seatNumber: 12 ,row:"A"},
    {id: 13,available: false,seatNumber: 1,row:"B"},
    {id: 14,available: false,seatNumber: 2,row:"B"},
    {id: 15,available: true,seatNumber: 3,row:"B"},
    {id: 16,available: false,seatNumber: 4,row:"B"},
    {id: 17,available: false,seatNumber: 5,row:"B"},
    {id: 18,available: false,seatNumber: 6,row:"B"},
    {id: 19,available: true,seatNumber: 7,row:"B"},
    {id: 20,available: false,seatNumber: 8,row:"B"},
    {id: 21,available: false,seatNumber: 9,row:"B"},
    {id: 22,available: false,seatNumber: 10,row:"B"},
    {id: 23,available: true,seatNumber: 11,row:"B"},
    {id: 24,available: false,seatNumber: 12,row:"B"},
    {id: 25,available: false,seatNumber: 1,row:"C"},
    {id: 26,available: false,seatNumber: 2,row:"C"},
    {id: 27,available: true,seatNumber: 3,row:"C"},
    {id: 28,available: false,seatNumber: 4,row:"C"},
    {id: 29,available: false,seatNumber: 5,row:"C"},
    {id: 30,available: true,seatNumber: 6,row:"C"},
    {id: 31,available: false,seatNumber: 7,row:"C"},
    {id: 32,available: true,seatNumber: 8,row:"C"},
    {id: 33,available: false,seatNumber: 9,row:"C"},
    {id: 34,available: false,seatNumber: 10,row:"C"},
    {id: 35,available: true,seatNumber: 11,row:"C"},
    {id: 36,available: false,seatNumber: 12,row:"C"},
    {id: 37,available: false,seatNumber: 1,row:"D"},
    {id: 38,available: false,seatNumber: 2,row:"D"},
    {id: 39,available: false,seatNumber: 3,row:"D"},
    {id: 40,available: true,seatNumber: 4,row:"D"},
    {id: 41,available: false,seatNumber: 5,row:"D"},
    {id: 42,available: false,seatNumber: 6,row:"D"},
    {id: 43,available: false,seatNumber: 7,row:"D"},
    {id: 44,available: true,seatNumber: 8,row:"D"},
    {id: 45,available: false,seatNumber: 9,row:"D"},
    {id: 46,available: false,seatNumber: 10,row:"D"},
    {id: 47,available: true,seatNumber: 11,row:"D"},
    {id: 48,available: false,seatNumber: 12,row:"D"}
];